version: '3'
services:
    l10dev-nginx:
        container_name: l10dev-nginx
        build:
            context: ./docker/nginx
        depends_on:
            - l10dev-app
        ports:
            - '80:80'
        volumes:
            - './:/src'
    l10dev-app:
        container_name: l10dev-app
        build:
            context: ./docker/php
        depends_on:
            - l10dev-mysql
        ports:
            - '5173:5173'
        volumes:
            - './:/src'
            - /src/node_modules
            - /src/vendor
            - './docker/php/php.ini:/usr/local/etc/php/php.ini'
    l10dev-mysql:
        image: 'mysql:8.0.33'
        command: '--max_allowed_packet=32505856'
        container_name: l10dev-mysql
        volumes:
            - './docker/mysql:/var/lib/mysql'
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=l10dev
        ports:
            - '3306:3306'
        cap_add:
            - SYS_NICE
    l10dev-redis:
        image: 'redis:alpine'
        container_name: l10dev-redis
        ports:
            - '16379:6379'
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-33306}:3306'
        cap_add:
            - SYS_NICE
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
networks:
    sail:
volumes:
    sail-mysql:
        driver: local
    sail-pgsql:
        driver: local
